### ISSUE TITLE
Typo in PaymentException path

### ISSUE THREAD

**Issue by sport24-mam** [RadarsofthouseDev/reepay-payment-for-magento2#12] opened 2022-04-28 07:38 UTC
https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/blob/eb61952726f6aa3c71a7087b27afcf8f5b409435/Helper/Data.php#L699

**Comment by RadarsofthouseDev** [comment] 2022-06-13 05:36
The issue is fixed on V 1.2.21
[https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/releases/tag/1.2.21](url)
Thank you :)

**Closed by RadarsofthouseDev** 2022-06-13 05:36 UTC
